[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.1,<4"]

[tool.flit.metadata]
module = "jupyterlite"
author = "JupyterLite Contributors"
description-file = "README.md"
license = "BSD-3-Clause"
home-page = "https://github.com/jupyterlite/jupyterlite"
requires-python = ">=3.7"
requires = [
    "doit",
    "entrypoints",
    "jupyter_core >=4.7",
    # TODO: support wheels https://github.com/jupyterlite/jupyterlite/issues/151
    # "wheel",
]
keywords = "jupyterlab,jupyter,notebook,schema,pyodide,browser,js,p5.js,doit"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Jupyter",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Pre-processors",
    "Topic :: Text Processing :: Markup :: HTML",
]

[tool.flit.scripts]
jupyter-lite = "jupyterlite.app:main"

[tool.flit.sdist]
include = [
    "src/jupyterlite/jupyterlite-*.tgz",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest-cov",
    "pytest-html",
    "pytest-xdist",
    "pytest",
]
lab = [
    "jupyterlab >=3.0,<4",
]
contents = [
    "jupyter_server",
]
serve = [
    "tornado >=6.1",
]
check = [
    "jsonschema >=3"
]

[tool.flit.entrypoints."jupyterlite.addon.v0"]
static = "jupyterlite.addons.static:StaticAddon"
federated_extensions = "jupyterlite.addons.federated_extensions:FederatedExtensionAddon"
settings = "jupyterlite.addons.settings:SettingsAddon"
contents = "jupyterlite.addons.contents:ContentsAddon"
lite = "jupyterlite.addons.lite:LiteAddon"
report = "jupyterlite.addons.report:ReportAddon"
serve = "jupyterlite.addons.serve:ServeAddon"
archive = "jupyterlite.addons.archive:ArchiveAddon"

[tool.tbump.version]
current = "0.1.0a5"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
  ((?P<channel>a|b|rc|.dev)(?P<release>\d+))?
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "src/jupyterlite/__init__.py"