name: jupyterlite-dev
# this is a conda/mamba environment for working on JupyterLite and upstreams

channels:
  - conda-forge
  - conda-forge/label/jupyterlite_pyodide_kernel_beta
  - conda-forge/label/jupyterlite_core_beta

dependencies:
  # build stuff
  - depfinder
  - nbstripout
  - ruff =0.1.7
  # demo stuff
  - ipywidgets >=8.0.4,<9
  - jupyter-server-proxy
  # extra docs tools
  - sphinx-autobuild
  # avoid 200mb mkl
  - nomkl

  # the chunk below populates `../examples/jupyter_lite_config.json`,
  # rewriting `anaconda.org` links to `conda-forge`'s GitHub releases
  ### FEDERATED EXTENSIONS ###
  - ipycytoscape
  - jupyterlab_miami_nights >=0.4.0
  - jupyterlab_widgets >=3.0.4,<4.0.0
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - jupyterlab-github >=4.0.0
  - jupyterlab-kernelspy >=4.0.0
  - jupyterlab-tour >=4.0.1
  # TODO: re-add after JupyterLab 4 compatibility
  # https://github.com/jupyterlite/jupyterlab-webrtc-docprovider/issues/16
  # - jupyterlab-webrtc-docprovider >=0.1.1
  - jupyterlab-night
  - jupyterlite-pyodide-kernel >=0.4.0b0
  # if a package is pinned with == `doit check` will ensure the version is pinned
  # in `docs/_build/_static/files/*.ipynb`
  - bqplot
  - ipycanvas
  - ipyleaflet
  - ipympl
  - ipyvue
  - ipyvuetify
  - plotly >=5.12.0
  ### FEDERATED EXTENSIONS ###

  # the chunk below gets copied from `../docs/environment.yml` by `doit env`
  ### DOCS ENV ###
  # runtimes
  - nodejs >=20,<21
  - python >=3.11,<3.12
  # build
  - doit >=0.34,<1
  - hatch >=1.6.3,<2
  - importlib_metadata
  - jsonschema >=3
  - jupyterlab >=4.2.4,<4.3
  - notebook >=7.2.0,<7.3
  - pip
  - pkginfo
  - python-libarchive-c
  - requests_cache
  - twine >=5.1.1
  - wheel
  # cli
  - wheel
  # docs
  - docutils >=0.18
  - myst-nb >=1
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxcontrib-mermaid
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts >=1.4.0
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # language packs and contents
  - jupyter_server >=1.11,<3
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab_server >=2.27.1,<3
  ### DOCS ENV ###
