name: jupyterlite-dev
# this is a conda/mamba environment for working on JupyterLite and upstreams

channels:
  - conda-forge/label/jupyterlab_rc
  - conda-forge

dependencies:
  # build stuff
  - black
  - flit >=3.1
  - isort
  - pyflakes
  - twine
  # demo stuff
  - jupyter-server-proxy
  - jupyterlab >=3.1.0rc1,<4
  - retrolab
  # extra docs tools
  - sphinx-autobuild

  # the chunk below populates `../examples/jupyter_lite_config.json`,
  # rewriting `anaconda.org` links to `conda-forge`'s GitHub releases
  ### FEDERATED EXTENSIONS ###
  - bqplot==0.12.29
  - ipycanvas==0.9.0
  - ipycytoscape==1.2.1
  - ipyleaflet==0.14.0
  - ipympl==0.7.0
  - jupyterlab_miami_nights
  - jupyterlab_widgets >=1,<2
  - jupyterlab-drawio
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - jupyterlab-kernelspy
  - jupyterlab-tour >=3.1.0
  - plotly >=5,<6
  - theme-darcula
  ### FEDERATED EXTENSIONS ###

  # the chunk below gets copied from `../docs/environment.yml` by `doit env`
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - jsonschema >=3
  - yarn <2
  # cli
  - wheel
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  ### DOCS ENV ###
