[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pyolite"
author = "JupyterLite Contributors"
home-page = "https://github.com/jtpio/jupyterlite"

