[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "nbformat"
author = "JupyterLite Contributors"
home-page = "https://github.com/jupyterlite/jupyterlite"
requires-python = ">=3.6"
