name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  # the chunk below gets copied to ../.binder/environment.yml
  ### DOCS ENV ###
  # runtimes
  - nodejs >=20,<21
  - python >=3.11,<3.12
  # build
  - doit >=0.34,<1
  - hatch >=1.6.3,<2
  - jsonschema >=3
  - jupyterlab >=4.1.1,<4.2
  - notebook >=7.1.0,<7.2
  - pip
  - pkginfo
  - python-libarchive-c
  - requests_cache
  - twine
  - wheel
  # cli
  - wheel
  # docs
  - docutils >=0.18
  - myst-nb >=1
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxcontrib-mermaid
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts >=1.4.0
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # language packs and contents
  - jupyter_server >=1.11,<3
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab_server >=2.8.1,<3
  ### DOCS ENV ###
