name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - jsonschema >=3
  - yarn <2
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # list of federated extensions for the demo site
  - jupyterlab-drawio
  - jupyterlab-tour >=3.1.0
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - theme-darcula
  ### DOCS ENV ###

  - pip:
      - plotly==5.0.0rc1
