name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  # the chunk below gets copied to ../.binder/environment.yml
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.9,<3.10
  # build
  - doit >=0.33,<0.34
  - flit >=3.7.1,!=3.5.0
  - jupyter-server-mathjax >=0.2.3
  - jsonschema >=3
  - pip
  - pkginfo
  - wheel
  - yarn <2
  # cli
  - wheel
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # language packs and contents
  - jupyter_server >=1.11,<2
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab_server >=2.8.1,<3
  ### DOCS ENV ###
