name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  # the chunk below gets copied to ../.binder/environment.yml
  ### DOCS ENV ###
  # runtimes
  - nodejs >=16,<17
  - python >=3.10,<3.11
  # build
  - doit >=0.34,<1
  - flit >=3.7.1,<4
  - jupyter-server-mathjax >=0.2.3
  - jsonschema >=3
  - pip
  - pkginfo
  - python-libarchive-c
  - requests_cache
  - wheel
  - yarn <2
  # cli
  - wheel
  # docs
  - docutils >=0.18
  - myst-nb
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # language packs and contents
  - jupyter_server >=1.11,<3
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab_server >=2.8.1,<3
  ### DOCS ENV ###
